name: Test Package

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Configure Poetry to not create virtualenvs
        run: poetry config virtualenvs.create false

      - name: Install dependencies
        run: poetry install --with test

      - name: Run tests
        env:
          khaya_api_key: ${{ secrets.KHAYA_API_KEY }}
        run: |
          echo "KHAYA_API_KEY = $khaya_api_key" 
          poetry run pytest --cov=khaya 